FROM node:18

WORKDIR /app
COPY package*.json ./
RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object
RUN npm install

ENV REACT_APP_API_URL=http://localhost:8141:80
ENV NODE_ENV=development

COPY . .

CMD ["npm", "start"]